name: smart_restaurant_finder
description: "Assessment Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.6.0
  badges: ^3.1.2
  animations: ^2.0.8
  simple_animations: ^5.0.2
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.20.3+1
  get: ^4.7.2
  google_fonts: ^6.3.2
  lottie: ^3.3.2
  firebase_ai: ^3.6.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.0

  #Sign-In
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/

  # Fonts configuration - only AppIcon.ttf
  fonts:
    - family: AppIcon
      fonts:
        - asset: assets/fonts/AppIcon.ttf